### ISSUE TITLE
Library compiled with Java 8

### ISSUE THREAD

**Issue by WonderCsabo** [aaronhe42/ThreeTen-Backport-Gson-Adapter#3]
The latest version (1.0.1) of the library was compiled with Java 8 target level. This makes the library unusable in Android, because the dexer can only use Java 7 compatible classes.

**Comment by aaronhe42** [comment]
@WonderCsabo Sorry about that. Just released 1.0.2 which is Java 7 compatible. It might take a few hours to be indexed by Maven/JCenter. Thanks.

**Comment by WonderCsabo** [comment]
No problem, and thanks for the quick release.
