### ISSUE TITLE
ZonedDateTimeConverter Throws UnsupportedOperationException In JsonElement

### ISSUE THREAD

**Issue by feinstein** [aaronhe42/ThreeTen-Backport-Gson-Adapter#7]
The `ZonedDateTimeConverter` calls `JsonElement.getAsString()` in:
```
@Override
    public ZonedDateTime deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
          throws JsonParseException {
        return FORMATTER.parse(json.getAsString(), ZonedDateTime.FROM);
    }
```

the `json.getAsString()` throws an `UnsupportedOperationException`, looking at its code it's clear why:

```
public String getAsString() {
    throw new UnsupportedOperationException(getClass().getSimpleName());
  }
```

So this makes me wonder, why are you using this? And how did this even worked for you?

**Comment by aaronhe42** [comment]
`JsonElement` is an abstract class. At runtime, it will be `JsonPrimitive`.

**Comment by feinstein** [comment]
Well, I am getting a `UnsupportedOperationException`, so `JsonElement` is being used.

**Comment by aaronhe42** [comment]
Can you please provide a sample app to demonstrate the issue?

**Comment by feinstein** [comment]
I can only provide a JSON input:

`
[{"id":0,"location":{"latitude":-22.967049,"longitude":-43.19096},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":649000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.965845,"longitude":-43.191102},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.965924,"longitude":-43.189954},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.96704,"longitude":-43.188935},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.968927,"longitude":-43.189933},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.969908,"longitude":-43.188015},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}},{"id":0,"location":{"latitude":-22.967715,"longitude":-43.19074},"timestamp":{"offset":{"totalSeconds":0,"id":"Z","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"zone":{"id":"UTC","rules":{"fixedOffset":true,"transitions":[],"transitionRules":[]}},"year":2018,"month":"JANUARY","dayOfMonth":2,"dayOfWeek":"TUESDAY","dayOfYear":2,"monthValue":1,"hour":20,"minute":10,"second":47,"nano":668000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}}]`

This is an `array` of `Report` objects, which includes an `id`, a `location` and a `ZonedDateTime` `timestamp`.

I am trying to convert it using `Retrofit` and `GSON`.

**Comment by aaronhe42** [comment]
This library only supports serialization of ISO8601 date strings. In the case of `ZonedDateTime`, the string would look like  [`"2010-08-20T10:43:46+08:00[Asia/Shanghai]"`](https://github.com/aaronhe42/ThreeTen-Backport-Gson-Adapter/blob/master/src/test/java/org/aaronhe/threetengson/ZonedDateTimeConverterTest.java#L32). You'll need a custom adapter to support your `timestamp` structure.

**Comment by feinstein** [comment]
Hmm I see, this should be on the documentations.

Coincidentally, I am updating my webservice so it would be using a small date string instead.
